### ISSUE TITLE
Feature Request: iCloud support

### ISSUE THREAD

**Issue by shaneparsons** [Trollpants/CloudOnce#2]
Correct me if I'm wrong, but Game Center does not handle cloud saves?

If there's a current method being used for iOS cloud saves let me know, otherwise, it would be awesome if iCloud support was added to the plugin.

**Comment by zynthar** [comment]
iCloud support is indeed already in the plugin.

**Comment by shaneparsons** [comment]
Ah that's awesome, sorry I didn't look into it further before opening the request.

Thanks for the plugin!
