### ISSUE TITLE
Failed to repackage resources

### ISSUE THREAD

**Issue by ResoDev** [Trollpants/CloudOnce#3]
**Hi.
Few days ago, I was able to build an apk without issues. Then I've added achievements and all of the sudden this error pops up when I try to build my game. I have really no clue of what's going on.**

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
G:\Android\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "G:/Android\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages com.google.firebase:com.amazon.ags:com.google.android.gms:com.google.example.games.mainlibproj:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4:com.unity3d.ads.android -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\firebase-common-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\gamecircle_lib\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-auth-base-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-basement-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-drive-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-games-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-nearby-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\play-services-tasks-9.0.2\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\support-v4-23.0.0\res" -S "C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res"

stderr[

]
stdout[
Configurations:
 (default)

Files:
  drawable\unityads_background_button_pause.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_background_button_pause.xml
  drawable\unityads_icon_play.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_play.xml
  drawable\unityads_icon_speaker_base.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_speaker_base.xml
  drawable\unityads_icon_speaker_triangle.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_speaker_triangle.xml
  drawable\unityads_icon_speaker_waves.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_speaker_waves.xml
  layout\unityads_button_audio_toggle.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_button_audio_toggle.xml
  layout\unityads_button_pause.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_button_pause.xml
  layout\unityads_view_video_paused.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_view_video_paused.xml
  layout\unityads_view_video_play.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_view_video_play.xml
  layout\unityads_view_video_play2.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_view_video_play2.xml
  values\values.xml
    Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\values\values.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable\unityads_background_button_pause.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_background_button_pause.xml
    drawable\unityads_icon_play.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_play.xml
    drawable\unityads_icon_speaker_base.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_speaker_base.xml
    drawable\unityads_icon_speaker_triangle.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_speaker_triangle.xml
    drawable\unityads_icon_speaker_waves.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\drawable\unityads_icon_speaker_waves.xml
  Type layout
    layout\unityads_button_audio_toggle.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_button_audio_toggle.xml
    layout\unityads_button_pause.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_button_pause.xml
    layout\unityads_view_video_paused.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_view_video_paused.xml
    layout\unityads_view_video_play.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_view_video_play.xml
    layout\unityads_view_video_play2.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\layout\unityads_view_video_play2.xml
  Type values
    values\values.xml
      Src: () C:\Users\mreso\Documents\Falling Delivery\Temp\StagingArea\android-libraries\unityads\res\values\values.xml
Including resources from package: G:\Android\platforms\android-24\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=cast_ic_notification_0.png
trying overlaySet Key=cast_ic_notification_1.png
trying overlaySet Key=cast_ic_notification_2.png
trying overlaySet Key=cast_ic_notification_connecting.xml
trying overlaySet Key=cast_ic_notification_on.png
trying overlaySet Key=common_full_open_on_phone.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_full_open_on_phone.png, for flavor mdpi-v4
found a match (1) for overlay file common_full_open_on_phone.png, for flavor tvdpi-v4
found a match (2) for overlay file common_full_open_on_phone.png, for flavor hdpi-v4
found a match (3) for overlay file common_full_open_on_phone.png, for flavor xhdpi-v4
found a match (4) for overlay file common_full_open_on_phone.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file common_google_signin_btn_icon_dark.xml, for flavor 
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor mdpi-v4
found a match (1) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor tvdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor hdpi-v4
found a match (3) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor xhdpi-v4
found a match (4) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_dark_focused.9.png, for flavor mdpi-v4
found a match (1) for overlay file common_google_signin_btn_icon_dark_focused.9.png, for flavor tvdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_dark_focused.9.png, for flavor hdpi-v4
found a match (3) for overlay file common_google_signin_btn_icon_dark_focused.9.png, for flavor xhdpi-v4
found a match (4) for overlay file common_google_signin_btn_icon_dark_focused.9.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_dark_normal.9.png, for flavor mdpi-v4
found a match (1) for overlay file common_google_signin_btn_icon_dark_normal.9.png, for flavor tvdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_dark_normal.9.png, for flavor hdpi-v4
found a match (3) for overlay file common_google_signin_btn_icon_dark_normal.9.png, for flavor xhdpi-v4
found a match (4) for overlay file common_google_signin_btn_icon_dark_normal.9.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_dark_pressed.9.png, for flavor mdpi-v4
found a match (1) for overlay file common_google_signin_btn_icon_dark_pressed.9.png, for flavor tvdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_dark_pressed.9.png, for flavor hdpi-v4
found a match (3) for overlay file common_google_signin_btn_icon_dark_pressed.9.png, for flavor xhdpi-v4
found a match (4) for overlay file common_google_signin_btn_icon_dark_pressed.9.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_light.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file common_google_signin_btn_icon_light.xml, for flavor 
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_light_disabled.9.png, for flavor mdpi-v4
found a match (1) for overlay file common_google_signin_btn_icon_light_disabled.9.png, for flavor tvdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_light_disabled.9.png, for flavor hdpi-v4
found a match (3) for overlay file common_google_signin_btn_icon_light_disabled.9.png, for flavor xhdpi-v4
found a match (4) for overlay file common_google_signin_btn_icon_light_disabled.9.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi-v4
overlayFile 2 has flavor hdpi-v4
overlayFile 3 has flavor xhdpi-v4
overlayFile 4 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_light_focused.9.png, for flavor mdpi-v4
found a match (1) for overlay file common_google_signin_btn_icon_light_focused.9.png, for flavor tvdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_light_focused.9.png, for flavor hdpi-v4
found a match (3) for overlay file common_google_signin_btn_icon_light_focused.9.png, for flavor xhdpi-v4
found a match (4) for overlay file common_google_signin_btn_icon_light_focused.9.png, for flavor xxhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor tvdpi<message truncated>

**Comment by zynthar** [comment]
https://github.com/Trollpants/CloudOnce/blob/master/.github/CONTRIBUTING.md#using-the-issue-tracker
